#!/bin/bash -l

#SBATCH --job-name=submit_monitor
#SBATCH --account=project-id
#SBATCH --partition=work
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:01:00

./SoftwareRun