#!/bin/bash -l

#SBATCH --job-name=submit_monitor
#SBATCH --account=coursesuwashpc
#SBATCH --partition=work
#SBATCH --ntasks=32
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --time=00:03:00
#SBATCH --output=slurm-32.out

srun -n 32 ./MonteCarloManyThread.out
      